### ISSUE TITLE
Error everytime a quest is removed

### ISSUE THREAD

**Issue by HadesDeadlyTom** [ESOUIMods/LibQuestData#18]
Hello, me and my friends have this UI error everytime we finish or abandon a quest : 

```
user:/AddOns/LibGPS/MapAdapter.lua:196: attempt to index a nil value
stack traceback:
user:/AddOns/LibGPS/MapAdapter.lua:196: in function 'MapAdapter:GetWorldSize'
user:/AddOns/LibGPS/TamrielOMeter.lua:271: in function 'TamrielOMeter:GetCurrentWorldSize'
user:/AddOns/LibGPS/TamrielOMeter.lua:307: in function 'TamrielOMeter:GetWorldGlobalRatio'
user:/AddOns/LibGPS/TamrielOMeter.lua:286: in function 'TamrielOMeter:GetLocalDistanceInMeters'
(tail call): ?
user:/AddOns/LibQuestData/LibQuestData_Scan.lua:611: in function 'OnQuestRemoved'
```

I have tried uninstalling every addon that i have and keeping only the libraries, the error show up anyway.
Here's what i have enabled :  
![image](https://user-images.githubusercontent.com/33090879/232559000-58d40c2d-5b55-4243-98ec-dce1c284c824.png)

We all have this error in my group of friends, we are french, is it maybe because of the game language ?

**Comment by Sharlikran** [comment]
@HadesDeadlyTom I am not sure why that happens. It should not be related to the language but rather the location of where you are standing.

Are you in a group when this happens and you abandon the quest because you choose not to do the quest?

**Comment by Sharlikran** [comment]
@HadesDeadlyTom Thank you.

Which mod do you use Quest Map or Destinations, or both Quest Map and Destinations?

**Comment by Sharlikran** [comment]
@HadesDeadlyTom I tested this today in Vvardenfel with the main story quest Dilemme divin and did not have any error.

1. While in game type in chat "/debuglogger stack on" without quotes
2. While in game type in chat "/debuglogger level debug" without quotes
3. Reload your UI or log out and log back in for the changes to take effect.
4. Reproduce the error by abandoning a quest while not in a group.
5. Provide a link to LibDebugLogger.lua located in your SavedVariables folder. To provide a link go to Sirinsidiator's [Log Viewer](https://sir.insidi.at/or/logviewer/), wait for it to process, and in the upper right under Sharing click Upload.

**Comment by HadesDeadlyTom** [comment]
@Sharlikran Sorry for the delay ! I use only Quest Map. I did what you told me, here is the file. Thank you !
https://sir.insidi.at/or/logviewer/PowVtF

**Comment by Sharlikran** [comment]
@HadesDeadlyTom The author does not have any idea how that could happen. So this because an issue where since you have the issue and I don't even when I play in French and the author, who is really good at knowing potential issues, then you would need to help figure it out.

To do that Rename your addons folder to something like `Addons_Bak`. Then install only QuestMap and its requirements. If it does not work then the issue is on your end and I have some ideas even though it will be hard for me to replicate.

If you do not have errors then you have a mod conflict and to find that you have to keep QuestMap installed but only reinstall one mod at a time. Once you install one and get the error uninstall it and it's requirements. Then move onto the next one. You can't install them all in blocks or you will not know which cause the error. One mod at a time and uninstall it if it causes an error. Do not reinstall BugCatcher so you can see the errors.

Let me know which mods cause it because there are mods that will sort of work but the older the get ZOS changes could be causing silent issues because there isn't any work being done on the mods. There are going to be mods that break with Necrom and some with the update after that. It is just going to happen because of the changes that are coming.

**Comment by Sharlikran** [comment]
Your log shows you have an older version of LibGPS version 68. The best way to update your mods is to open Minion and right click each one and choose reinstall. The current version of LibGPS is version 69.

**Comment by HadesDeadlyTom** [comment]
![image](https://github.com/ESOUIMods/LibQuestData/assets/33090879/8fe222a9-22ea-40fe-afdb-31d5f08bafb2)
My version of LibGPS seem to be up to date acording to minion.

Thanks for your help, since i installed the bugcatcher addon the error is no longer bothering me. I can play like that no problem.

**Comment by Sharlikran** [comment]
Minion doesn't always report the proper version or update properly. The version numbers I'm telling you about are from the log you provided.

The next versions will require the current version of the libraries. So if after Monday when Necrom is available to all! If you still have the error with BugCatcher installed then you have an issue where QuestMap and LibQuestData is loading with older libraries.

What that means is that the game can not even detect the proper version of the library.

Which means you have OneDrive issues, or multiple Addons folder locations or something odd that causes you to be able to load the game and run current mods like QuestMap with outdated libraries and the game should not be able to do that.

So take your time but at some point this needs to be resolved or you could have issues with other mods and it could be worse for them because they will break too many part of your UI.

**Comment by Sharlikran** [comment]
So lets look at this again Tuesday after Necrom launches.

**Comment by HadesDeadlyTom** [comment]
Ok, I'll take a look, but this is a new install of both eso and minion, so I can't think of another addon location. I will take the time to find out and will let you know of my discovery if I find anything. 
I think i'll try to install LibGPS manualy to be sure of the version.

Thanks again for your time and help it's really appreciated.

**Comment by Sharlikran** [comment]
@HadesDeadlyTom What is the status of this because as mentioned I don't have that issue even when I change to French.

**Comment by HadesDeadlyTom** [comment]
> @HadesDeadlyTom What is the status of this because as mentioned I don't have that issue even when I change to French.

Hello @Sharlikran i'm sorry i thouth i had informed you, you were right. Since Necrom launch the error is gone ! 
Thanks for your help, i'm closing the issue.
